import { Montserrat} from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";



const myFont= Montserrat({
  subsets:["latin"],
  weight:["400", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={myFont.className}
      >
       
        {children}
        
      </body>
    </html>
  );
}
